# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rqrcode_png/all/rqrcode_png.rbi
#
# rqrcode_png-0.1.5

module RqrcodePng
end
module RQRCodePNG
end
class RQRCodePNG::Sequence
  def border_width; end
  def dark_squares_only(&block); end
  def img_size; end
  def initialize(qr_code); end
end
class RQRCodePNG::Image
  def blank_img(bg_color = nil); end
  def img_size; end
  def initialize(qr_code); end
  def render(bg_color = nil); end
end
module RQRCodePNG::QRCodeExtensions
  def to_img(bg_color = nil); end
end
class RQRCode::QRCode
  include RQRCodePNG::QRCodeExtensions
end
